name: TreeTwerk
authors: [RaiTaki, Cazcez]
dev-url: http://github.com/Chereza/TreeTwerk-remastered
main: treetwerk.main.Main
version: 0.1.2
api-version: 1.13

commands:
  TreeTwerk:
    description: it does what it needs to do